services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: helixdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d helixdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "26379:6379"

  helix:
    image: whereasjovially/helix:electra-with-proofs
    container_name: helix
    volumes:
      - ./config.yml:/app/config.yml
      - ./hoodi.json:/app/network_config.json
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      postgres:
        condition: service_healthy   # Ensure PostgreSQL is healthy before starting Helix
      redis:
        condition: service_started
    ports:
      - "4040:4040"
      - "8080:8080"
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      - RUST_LOG=debug    # Set the log level to DEBUG